### ISSUE TITLE
failed to import bridging header '/Users/winterrain/Downloads/PCastDemo-master/ios/Bridging-Header.h'

### ISSUE THREAD

**Issue by raviatri** [PhenixP2P/PCastDemo#3]
Hi I am trying to test the Demo iOS app but it fail and give this issues:-
```
/Users/winterrain/Downloads/PCastDemo-master/ios/Bridging-Header.h:12:9: note: in file included from /Users/winterrain/Downloads/PCastDemo-master/ios/Bridging-Header.h:12:
#import "PhenixPCast.h"
        ^
/Users/winterrain/Downloads/PCastDemo-master/ios/iOSSDK/PCast/PhenixPCast.h:6:9: error: 'PCast/PhenixMediaStream.h' file not found
#import "PCast/PhenixMediaStream.h"
        ^
<unknown>:0: error: failed to import bridging header '/Users/winterrain/Downloads/PCastDemo-master/ios/Bridging-Header.h'
```
Followed all steps mentioned in README file.
I also attached the screen shot please check.
![screen shot 2017-04-19 at 7 07 09 pm](https://cloud.githubusercontent.com/assets/11192047/25182812/69d8ab44-2533-11e7-8efc-9a414b00bec0.png)

**Comment by andreas-schuler** [comment]
Hi Ravi,

I believe that you may have to update your local repository. Run a `git pull` followed by running the `git-submodule-setup.sh` script.

If all else fails, I would recommend to just clone the repo again.

Please let me know if this works so I can close the issue.

Andreas

**Comment by raviatri** [comment]
Hi Andreas thanks for the quick reply, I followed your instruction pull out new clone in to my desktop. And after running git-submodule-setup.sh script it gives below authentication error:-

```
WinTerrains-MacBook-2:PCastDemo winterrain$ ./git-submodule-setup.sh
running git-submodule setup
Submodule 'AndroidSDK' (git@github.com:PhenixP2P/AndroidSDK.git) registered for path 'android/AndroidSDK'
Submodule 'iOSSDK' (git@github.com:PhenixP2P/iOSSDK.git) registered for path 'ios/iOSSDK'
Cloning into '/Users/winterrain/Desktop/PCastDemo/android/AndroidSDK'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

```
I think it failed to download SDK, may i know how can i authenticate and install SDK in Demo project.

**Comment by kylebank** [comment]
Hi Ravi,

We typically sign mutual NDAs with all potential customers and set up a time to chat about their use case and pricing prior to providing trail access. Please email me at kyle.bank@phenixp2p.com to set up a brief call.

Thanks,

Kyle

**Comment by kylebank** [comment]
Hi Ravi,

May I ask which organization you are working with?

Thanks,
Kyle

**Comment by raviatri** [comment]
Hi Kyle 
We  already signed NDA with you guys with this email id:- cvoalex@gmail.com.
Can you please help me out from this authentication issue.
 If any other information you require from me to authenticate my self please let know.

**Comment by kylebank** [comment]
Hi Ravi, no problem. I will add you to the GitHub group. Please let us know if you have any further issues.

**Comment by raviatri** [comment]
Hi Thanks, i cloned repo and run command git-submodule-setup.sh successfully but there is no iOSSDK folder and files in my project folder. Is this git-submodule-setup.sh file is updated?

**Comment by andreas-schuler** [comment]
Can you share with us the output from running git-submodule-setup.sh? It sounds to me that there is an issue with git-lfs.

Do you not have any files in `./ios/iOSSDK`? If you do, what does `./ios/iOSSDK/lib` look like in terms of the files it contains?

**Comment by raviatri** [comment]
Output from running git-submodule-setup.sh-

```
RAVIs-MacBook-Pro:PCastDemo SHARMA$ ./git-submodule-setup.sh
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log
versionCompare requires a minimum of two arguments to compare versions.
./git-submodule-setup.sh: line 118: [: -lt: unary operator expected
running git-submodule setup
Submodule 'AndroidSDK' (git@github.com:PhenixP2P/AndroidSDK.git) registered for path 'android/AndroidSDK'
Submodule 'iOSSDK' (git@github.com:PhenixP2P/iOSSDK.git) registered for path 'ios/iOSSDK'
Cloning into '/Users/SHARMA/Documents/PCastDemo/android/AndroidSDK'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PhenixP2P/AndroidSDK.git' into submodule path '/Users/SHARMA/Documents/PCastDemo/android/AndroidSDK' failed
Failed to clone 'android/AndroidSDK'. Retry scheduled
Cloning into '/Users/SHARMA/Documents/PCastDemo/ios/iOSSDK'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PhenixP2P/iOSSDK.git' into submodule path '/Users/SHARMA/Documents/PCastDemo/ios/iOSSDK' failed
Failed to clone 'ios/iOSSDK'. Retry scheduled
Cloning into '/Users/SHARMA/Documents/PCastDemo/android/AndroidSDK'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:PhenixP2P/AndroidSDK.git' into submodule path '/Users/SHARMA/Documents/PCastDemo/android/AndroidSDK' failed
Failed to clone 'android/AndroidSDK' a second time, aborting
RAVIs-MacBook-Pro:PCastDemo SHARMA$ 
```

--> No folder with name in `./ios/iOSSDK` PCastDemo/ios.

**Comment by n10s** [comment]
Hi Ravi,

It looks like you don't have git-lfs installed. To do this on a Mac, you need to ensure that Homebrew is installed and run "brew install git-lfs" in a terminal.

It also looks like you haven't accepted the invite to the Github group, which you will need to do in order to access the mobile SDK.

Thanks,
Nicholas

**Comment by raviatri** [comment]
Hi I installed git-lfs but it run with a warning message-

```
RAVIs-MacBook-Pro:PCastDemo SHARMA$ brew install git-lfs
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing dependencies for git-lfs: go
==> Installing git-lfs dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.6.2.src.tar.gz
Already downloaded: /Users/SHARMA/Library/Caches/Homebrew/go-1.6.2.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10.8.tar.gz
Already downloaded: /Users/SHARMA/Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/SHARMA/Library/Logs/Homebrew/go/01.make.bash:
	/private/tmp/go-20170420-2105-1t4vunu/go/gobootstrap/src/cmd/go/clean.go:118 +0x1bb fp=0xc20802bd18 sp=0xc20802ba38
main.runClean(0x3f9ae0, 0xc20800a030, 0x1, 0x1)
	/private/tmp/go-20170420-2105-1t4vunu/go/gobootstrap/src/cmd/go/clean.go:79 +0x9c fp=0xc20802bd98 sp=0xc20802bd18
main.main()
	/private/tmp/go-20170420-2105-1t4vunu/go/gobootstrap/src/cmd/go/main.go:163 +0x608 fp=0xc20802bf98 sp=0xc20802bd98
runtime.main()
	/usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc20802bfe0 sp=0xc20802bf98
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20802bfe8 sp=0xc20802bfe0

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
RAVIs-MacBook-Pro:PCastDemo SHARMA$ 
```

And one thing is it possible to do a call in next 15 mins?

**Comment by sempi** [comment]
Did you try `brew update`?

**Comment by sempi** [comment]
Re call, yes we can talk send us an email so we can share call in number.

**Comment by kylebank** [comment]
Ravi, you can reach us via email at info@phenixp2p.com and we can share a call in number with you.

**Comment by raviatri** [comment]
hey team thanks for your support i have tested it and it is working very well.
Thanks a lot!!! :)
